/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './pages/__root'

// Create Virtual Routes

const LoginIndexLazyImport = createFileRoute('/login/')()
const HomeIndexLazyImport = createFileRoute('/home/')()

// Create/Update Routes

const LoginIndexLazyRoute = LoginIndexLazyImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/login/index.lazy').then((d) => d.Route))

const HomeIndexLazyRoute = HomeIndexLazyImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/home/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/home': typeof HomeIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
}

export interface FileRoutesByTo {
  '/home': typeof HomeIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/home/': typeof HomeIndexLazyRoute
  '/login/': typeof LoginIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/home' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/home' | '/login'
  id: '__root__' | '/home/' | '/login/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  HomeIndexLazyRoute: typeof HomeIndexLazyRoute
  LoginIndexLazyRoute: typeof LoginIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  HomeIndexLazyRoute: HomeIndexLazyRoute,
  LoginIndexLazyRoute: LoginIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/home/",
        "/login/"
      ]
    },
    "/home/": {
      "filePath": "home/index.lazy.tsx"
    },
    "/login/": {
      "filePath": "login/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
